steps:
  - name: node:20.0.0
    entrypoint: npm
    args: ["install"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'bash'
      - '-c'
      - |
        echo "GOOGLE_PROJECT_ID: ${_GOOGLE_PROJECT_ID}" >> .env.yaml 
        echo "GOOGLE_PROJECT_REGION: ${_GOOGLE_PROJECT_REGION}" >> .env.yaml
        echo "TELEGRAM_BOT_TOKEN: ${_GOOGLE_PROJECT_REGION}" >> .env.yaml
        echo "FUNCTION_NAME: ${_FUNCTION_NAME}" >> .env.yaml
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "${_FUNCTION_NAME}",
        "--runtime",
        "nodejs20",
        "--trigger-http",
        "--allow-unauthenticated",
        "--region",
        "${_GOOGLE_PROJECT_REGION}",
        "--project",
        "${_GOOGLE_PROJECT_ID}",
        "--entry-point",
        "${_ENTRY_POINT}",
        "--env-vars-file",
        ".env.yaml"
      ]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY
