steps:
  - name: node:20.0.0
    entrypoint: npm
    args: ["install"]
  - name: 'bash'
    args:
      - '-c'
      - |
        echo "GOOGLE_CLOUD_PROJECT_ID: ${_GOOGLE_CLOUD_PROJECT_ID}" >> .env.yaml 
        echo "GOOGLE_CLOUD_REGION: ${_GOOGLE_CLOUD_REGION}" >> .env.yaml
        echo "TELEGRAM_BOT_TOKEN: ${_TELEGRAM_BOT_TOKEN}" >> .env.yaml
        echo "FUNCTION_NAME: ${_FUNCTION_NAME}" >> .env.yaml
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "${_FUNCTION_NAME}",
        "--runtime",
        "nodejs20",
        "--trigger-http",
        "--allow-unauthenticated",
        "--region",
        "${_GOOGLE_CLOUD_REGION}",
        "--project",
        "${_GOOGLE_CLOUD_PROJECT_ID}",
        "--entry-point",
        "${_ENTRY_POINT}",
        "--env-vars-file",
        ".env.yaml"
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "add-invoker-policy-binding",
        "${_FUNCTION_NAME}",
        "--region",
        "${_GOOGLE_CLOUD_REGION}",
        "--project",
        "${_GOOGLE_CLOUD_PROJECT_ID}",
        "--member",
        "allUsers"
      ]
      
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY
